/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package yazilim_muhendisligi_odev3;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
    public static boolean Hesaplama(ArrayList<Integer> array,int birler_bas, int onlar_bas, int yuzler_bas) {
        boolean sonuc=false;
        int olusan_sayi=0;
            if( 0<=birler_bas && birler_bas<10 && 0<=onlar_bas && onlar_bas<10 && 0<=yuzler_bas && yuzler_bas<10 ){
                olusan_sayi= (yuzler_bas*100) + (onlar_bas*10) + (birler_bas);
                for(int i=0; i<array.size();i++){
                    if(olusan_sayi==array.get(i)){
                        sonuc=true;
                    }
    
                }
    
            }
            return sonuc;
    
        }
}
