/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package yazilim_muhendisligi_odev3;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
     //Girilen sayiların toplamı 3 haneli ve listede mevcutsa true donecek.
     @Test
     public void Test1() {
         ArrayList<Integer> array = new ArrayList<>(Arrays.asList(125, 547, 488,533));
         assertTrue(App.Hesaplama(array,7,4,5));
     }
      //Girilen 1.sayi 0-9 arasında degilse false donecek.
     @Test
     public void Test2() {
         ArrayList<Integer> array = new ArrayList<>(Arrays.asList(125, 547, 488,533));
         assertFalse(App.Hesaplama(array,13,2,8));
     }
     // //Girilen sayilar 0-9 arasında fakat mevcut liste bos ise false donecek.
     @Test
     public void Test3() {
         ArrayList<Integer> array = new ArrayList<>(Arrays.asList());
         assertFalse(App.Hesaplama(array,2,9,1));
     }
     //Girilen 3.sayi 0-9 arasında degilse false donecek.
     @Test
     public void Test4() {
         ArrayList<Integer> array = new ArrayList<>(Arrays.asList(125, 547, 488,533));
         assertFalse(App.Hesaplama(array,8,8,354));
     }
     @Test
     //Girilen sayilar negatif ise false donecek.
     public void Test5() {
         ArrayList<Integer> array = new ArrayList<>(Arrays.asList(125, 547, 488,533));
         assertFalse(App.Hesaplama(array,-2,4,7));
     }
}
